import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Load the data generated by the processing script
pixel_csv = "C:/Users/dredhu01/Box/CEE0189/output/Step3/pixel_composites_BEAST_from_local.csv"
pixel_data = pd.read_csv(pixel_csv)


def plot_area_comparison(data, area_prefix="Cali"):
    pre_pixels = data[data.study_area == f"{area_prefix}_prefire"]["radiance"].values
    post_pixels = data[data.study_area == f"{area_prefix}_postfire"]["radiance"].values

    # Ensure equal length for scatter plot if indices don't align perfectly
    # (though BEAST pixels usually should)
    min_len = min(len(pre_pixels), len(post_pixels))
    pre_pixels, post_pixels = pre_pixels[:min_len], post_pixels[:min_len]

    plt.figure(figsize=(6, 6))
    plt.scatter(pre_pixels, post_pixels, alpha=0.3, s=10)

    # Diagonal reference line
    max_val = max(pre_pixels.max(), post_pixels.max()) if len(pre_pixels) > 0 else 10
    plt.plot([0, max_val], [0, max_val], 'r--', label="1:1 Line")

    plt.xlabel("Pre-fire radiance (BEAST Trend Median)")
    plt.ylabel("Post-fire radiance (BEAST Trend Median)")
    plt.title(f"Pixel-level VIIRS NTL recovery: {area_prefix}")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.show()


if __name__ == "__main__":
    plot_area_comparison(pixel_data, "Cali")
